export const FETCH_CITIES_PENDING = 'FETCH_CITIES_PENDING';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';

export const CREATE_LOCATION_PENDING = 'CREATE_LOCATION_PENDING';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_ERROR = 'CREATE_LOCATION_ERROR';

export const EDIT_LOCATION_PENDING = 'EDIT_LOCATION_PENDING';
export const EDIT_LOCATION_SUCCESS = 'EDIT_LOCATION_SUCCESS';
export const EDIT_LOCATION_ERROR = 'EDIT_LOCATION_ERROR';

export const DELETE_LOCATION_PENDING = 'DELETE_LOCATION_PENDING';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_ERROR = 'DELETE_LOCATION_ERROR';

export const GET_CITIES = 'GET_CITIES';
export const SEND_FORM_LOCATION = 'SEND_FORM_LOCATION';
export const EDIT_FORM_LOCATION = 'EDIT_FORM_LOCATION';
export const DELETE_FORM_LOCATION = 'DELETE_FORM_LOCATION';
